#!/bin/sh
# From - rsyncd
#
# rsyncd - this script starts and stops the rsyncd daemon
# Originally from - rsyncd
#
# chkconfig:   - 85 15
# description:  rsyncd
# processname: rsync
# config:      /etc/rsyncd.conf
# config:      /etc/sysconfig/rsyncd
# pidfile:     /var/run/rsyncd.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

rsyncd="/usr/bin/rsync"
prog=$(basename $rsyncd)

conffile="/etc/rsyncd.conf"
pidfile=/var/run/rsyncd.pid

[ -f /etc/sysconfig/rsyncd ] && . /etc/sysconfig/rsyncd

lockfile=/var/lock/subsys/rsyncd

start() {
    [ -x $rsyncd ] || exit 5
    [ -f $conffile ] || exit 6
    echo -n $"Starting $prog: "
    daemon $rsyncd --daemon
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile && rm -f $pidfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac